In [554]:
import pandas as pd
import numpy as np
# import torch
from torch import tensor, from_numpy, nn, optim, float32, reshape
from torch.utils.data import TensorDataset, DataLoader
from torchvision import transforms
from sklearn.preprocessing import Normalizer, LabelBinarizer
from sklearn.model_selection import train_test_split

In [555]:
df = pd.read_csv("housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-117.61,34.13,21.0,8416.0,1386.0,4308.0,1341.0,4.4611,INLAND,164600.0
1,-117.37,33.98,52.0,201.0,44.0,130.0,24.0,2.0250,INLAND,125000.0
2,-118.34,33.89,36.0,2274.0,411.0,1232.0,423.0,5.3730,<1H OCEAN,244500.0
3,-118.92,35.13,29.0,1297.0,262.0,909.0,253.0,1.9236,INLAND,106300.0
4,-121.80,37.23,18.0,3179.0,526.0,1663.0,507.0,5.9225,<1H OCEAN,265800.0

In [556]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
ocean_proximity       False
median_house_value    False
dtype: bool

In [557]:
df_filled = df.fillna(method="bfill", axis=1)
df_filled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-117.61,34.13,21.0,8416.0,1386.0,4308.0,1341.0,4.4611,INLAND,164600.0
1,-117.37,33.98,52.0,201.0,44.0,130.0,24.0,2.025,INLAND,125000.0
2,-118.34,33.89,36.0,2274.0,411.0,1232.0,423.0,5.373,<1H OCEAN,244500.0
3,-118.92,35.13,29.0,1297.0,262.0,909.0,253.0,1.9236,INLAND,106300.0
4,-121.8,37.23,18.0,3179.0,526.0,1663.0,507.0,5.9225,<1H OCEAN,265800.0
...,...,...,...,...,...,...,...,...,...,...
16507,-119.53,36.55,34.0,2065.0,343.0,1041.0,313.0,3.2917,INLAND,111500.0
16508,-122.4,37.73,50.0,1947.0,411.0,1170.0,384.0,3.4769,NEAR BAY,238700.0
16509,-118.41,33.92,29.0,1436.0,401.0,674.0,343.0,3.6389,<1H OCEAN,275000.0
16510,-117.08,32.62,36.0,1674.0,309.0,818.0,307.0,3.4773,NEAR OCEAN,150400.0
16511,-117.05,32.72,35.0,3669.0,617.0,1694.0,585.0,3.9485,NEAR OCEAN,133900.0

In [558]:
binarizer = LabelBinarizer()
df_filled["ocean_proximity"] = binarizer.fit_transform(df_filled["ocean_proximity"])
df_filled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-117.61,34.13,21.0,8416.0,1386.0,4308.0,1341.0,4.4611,0,164600.0
1,-117.37,33.98,52.0,201.0,44.0,130.0,24.0,2.025,0,125000.0
2,-118.34,33.89,36.0,2274.0,411.0,1232.0,423.0,5.373,1,244500.0
3,-118.92,35.13,29.0,1297.0,262.0,909.0,253.0,1.9236,0,106300.0
4,-121.8,37.23,18.0,3179.0,526.0,1663.0,507.0,5.9225,1,265800.0
...,...,...,...,...,...,...,...,...,...,...
16507,-119.53,36.55,34.0,2065.0,343.0,1041.0,313.0,3.2917,0,111500.0
16508,-122.4,37.73,50.0,1947.0,411.0,1170.0,384.0,3.4769,0,238700.0
16509,-118.41,33.92,29.0,1436.0,401.0,674.0,343.0,3.6389,1,275000.0
16510,-117.08,32.62,36.0,1674.0,309.0,818.0,307.0,3.4773,0,150400.0
16511,-117.05,32.72,35.0,3669.0,617.0,1694.0,585.0,3.9485,0,133900.0

In [559]:
x = df_filled.drop("median_house_value", axis=1)
y = df_filled["median_house_value"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)
x_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
15137,-121.91,37.31,16.0,2962.0,898.0,1555.0,795.0,2.5804,1
4793,-121.83,37.35,31.0,2914.0,715.0,3547.0,645.0,3.7143,1
4709,-124.16,40.8,52.0,2167.0,480.0,908.0,451.0,1.6111,0
7652,-121.8,39.75,28.0,2551.0,378.0,1011.0,374.0,4.3309,0
2500,-118.34,33.84,36.0,1407.0,231.0,676.0,231.0,5.269,1
...,...,...,...,...,...,...,...,...,...
698,-122.0,37.31,28.0,3811.0,585.0,1795.0,581.0,7.8383,1
9572,-122.5,37.6,35.0,2197.0,369.0,971.0,326.0,4.25,0
4653,-118.21,34.11,32.0,2759.0,499.0,1661.0,533.0,4.3812,1
14369,-118.33,33.91,39.0,1224.0,312.0,1106.0,333.0,3.3491,1
6659,-121.34,38.59,23.0,2912.0,421.0,1132.0,410.0,5.9174,0

In [560]:
normalizer = Normalizer()
x_train_norm = normalizer.fit_transform(x_train)
x_test_norm = normalizer.transform(x_test)

In [561]:
from_numpy(y_train.values.astype(np.float32))

tensor([216300., 178600.,  74700.,  ..., 228200., 181800., 225900.])

In [562]:
x_train_tensor = from_numpy(x_train_norm).to(float32)
x_test_tensor = from_numpy(x_test_norm).to(float32)
y_train_tensor = from_numpy(y_train.values.astype(np.float32))
y_test_tensor = from_numpy(y_test.values.astype(np.float32))

In [563]:
class NeuralNetwork(nn.Module):
	def __init__(self):
		super(NeuralNetwork, self).__init__()
		self.flatten = nn.Flatten()
		self.layer_stack = nn.Sequential(
			nn.Linear(9, 1)
		)

	def forward(self, x):
		x = self.flatten(x)
		logits = self.layer_stack(x)
		return logits

model = NeuralNetwork().to('cpu')
print(model)
# list(model.named_parameters())
# model.layer_stack[0].weight.data

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (layer_stack): Sequential(
    (0): Linear(in_features=9, out_features=1, bias=True)
  )
)

In [564]:
criterion = nn.MSELoss()
optimiser = optim.SGD(model.parameters(), lr = 0.001)

In [565]:
# def train_loop(features, labels, model, loss_fn, optimiser):
# 	dataset = TensorDataset(features, labels)
# 	dl = DataLoader(dataset)

# 	size = len(dataset)
# 	# for batch, (X, y) in enumerate(dl):
# 	# 	y_hat = model(X)
# 	# 	loss = loss_fn(y_hat, y)

# 	# 	optimiser.zero_grad()
# 	# 	loss.backward()
# 	# 	optimiser.step()

# 	# 	if batch % 100 == 0:
# 	# 		current = batch * len(X)
# 	# 		print(f"loss: {loss.item() ** 0.5} [{current}/{size}]")
# 	y_hat = model(features)
# 	loss = loss_fn(y_hat, labels)

# 	optimiser.zero_grad()
# 	loss.backward()
# 	optimiser.step()

# 	print(f"loss")

# train_loop(x_train_tensor, y_train_tensor, model, criterion, optimiser)

In [566]:
model(x_train_tensor)
# reshape(model(x_train_tensor),(len(x_train_tensor),))

tensor([[-0.3218],
        [-0.3792],
        [-0.3286],
        ...,
        [-0.3495],
        [-0.3719],
        [-0.3318]], grad_fn=<AddmmBackward0>)

In [567]:
reshape(model(x_train_tensor), (-1,))

tensor([-0.3218, -0.3792, -0.3286,  ..., -0.3495, -0.3719, -0.3318],
       grad_fn=<ReshapeAliasBackward0>)

In [568]:

n_epochs = 5000
for epoch in range(n_epochs):
	print(f"Epoch {epoch + 1}\n-------------------------------")
	y_hat = reshape(model(x_train_tensor), (-1,))
	loss = criterion(y_hat, y_train_tensor)

	optimiser.zero_grad()
	loss.backward()
	optimiser.step()

	print(f"loss: {loss}")

Epoch 1
-------------------------------
loss: 56214315008.0
Epoch 2
-------------------------------
loss: 55877419008.0
Epoch 3
-------------------------------
loss: 55543173120.0
Epoch 4
-------------------------------
loss: 55211556864.0
Epoch 5
-------------------------------
loss: 54882529280.0
Epoch 6
-------------------------------
loss: 54556086272.0
Epoch 7
-------------------------------
loss: 54232199168.0
Epoch 8
-------------------------------
loss: 53910867968.0
Epoch 9
-------------------------------
loss: 53592051712.0
Epoch 10
-------------------------------
loss: 53275734016.0
Epoch 11
-------------------------------
loss: 52961902592.0
Epoch 12
-------------------------------
loss: 52650524672.0
Epoch 13
-------------------------------
loss: 52341604352.0
Epoch 14
-------------------------------
loss: 52035092480.0
Epoch 15
-------------------------------
loss: 51730989056.0
Epoch 16
-------------------------------
loss: 51429273600.0
Epoch 17
-------------------------------
loss: 51129921536.0
Epoch 18
-------------------------------
loss: 50832928768.0
Epoch 19
-------------------------------
loss: 50538258432.0
Epoch 20
-------------------------------
loss: 50245902336.0
Epoch 21
-------------------------------
loss: 49955844096.0
Epoch 22
-------------------------------
loss: 49668055040.0
Epoch 23
-------------------------------
loss: 49382522880.0
Epoch 24
-------------------------------
loss: 49099239424.0
Epoch 25
-------------------------------
loss: 48818163712.0
Epoch 26
-------------------------------
loss: 48539299840.0
Epoch 27
-------------------------------
loss: 48262627328.0
Epoch 28
-------------------------------
loss: 47988121600.0
Epoch 29
-------------------------------
loss: 47715774464.0
Epoch 30
-------------------------------
loss: 47445561344.0
Epoch 31
-------------------------------
loss: 47177469952.0
Epoch 32
-------------------------------
loss: 46911471616.0
Epoch 33
-------------------------------
loss: 46647574528.0
Epoch 34
-------------------------------
loss: 46385741824.0
Epoch 35
-------------------------------
loss: 46125965312.0
Epoch 36
-------------------------------
loss: 45868216320.0
Epoch 37
-------------------------------
loss: 45612494848.0
Epoch 38
-------------------------------
loss: 45358784512.0
Epoch 39
-------------------------------
loss: 45107060736.0
Epoch 40
-------------------------------
loss: 44857315328.0
Epoch 41
-------------------------------
loss: 44609527808.0
Epoch 42
-------------------------------
loss: 44363677696.0
Epoch 43
-------------------------------
loss: 44119764992.0
Epoch 44
-------------------------------
loss: 43877756928.0
Epoch 45
-------------------------------
loss: 43637657600.0
Epoch 46
-------------------------------
loss: 43399434240.0
Epoch 47
-------------------------------
loss: 43163082752.0
Epoch 48
-------------------------------
loss: 42928582656.0
Epoch 49
-------------------------------
loss: 42695925760.0
Epoch 50
-------------------------------
loss: 42465087488.0
Epoch 51
-------------------------------
loss: 42236071936.0
Epoch 52
-------------------------------
loss: 42008842240.0
Epoch 53
-------------------------------
loss: 41783402496.0
Epoch 54
-------------------------------
loss: 41559724032.0
Epoch 55
-------------------------------
loss: 41337802752.0
Epoch 56
-------------------------------
loss: 41117622272.0
Epoch 57
-------------------------------
loss: 40899166208.0
Epoch 58
-------------------------------
loss: 40682430464.0
Epoch 59
-------------------------------
loss: 40467390464.0
Epoch 60
-------------------------------
loss: 40254042112.0
Epoch 61
-------------------------------
loss: 40042360832.0
Epoch 62
-------------------------------
loss: 39832342528.0
Epoch 63
-------------------------------
loss: 39623970816.0
Epoch 64
-------------------------------
loss: 39417237504.0
Epoch 65
-------------------------------
loss: 39212122112.0
Epoch 66
-------------------------------
loss: 39008612352.0
Epoch 67
-------------------------------
loss: 38806704128.0
Epoch 68
-------------------------------
loss: 38606381056.0
Epoch 69
-------------------------------
loss: 38407622656.0
Epoch 70
-------------------------------
loss: 38210428928.0
Epoch 71
-------------------------------
loss: 38014779392.0
Epoch 72
-------------------------------
loss: 37820661760.0
Epoch 73
-------------------------------
loss: 37628067840.0
Epoch 74
-------------------------------
loss: 37436985344.0
Epoch 75
-------------------------------
loss: 37247406080.0
Epoch 76
-------------------------------
loss: 37059313664.0
Epoch 77
-------------------------------
loss: 36872687616.0
Epoch 78
-------------------------------
loss: 36687532032.0
Epoch 79
-------------------------------
loss: 36503826432.0
Epoch 80
-------------------------------
loss: 36321562624.0
Epoch 81
-------------------------------
loss: 36140732416.0
Epoch 82
-------------------------------
loss: 35961315328.0
Epoch 83
-------------------------------
loss: 35783307264.0
Epoch 84
-------------------------------
loss: 35606691840.0
Epoch 85
-------------------------------
loss: 35431464960.0
Epoch 86
-------------------------------
loss: 35257614336.0
Epoch 87
-------------------------------
loss: 35085123584.0
Epoch 88
-------------------------------
loss: 34913988608.0
Epoch 89
-------------------------------
loss: 34744197120.0
Epoch 90
-------------------------------
loss: 34575728640.0
Epoch 91
-------------------------------
loss: 34408587264.0
Epoch 92
-------------------------------
loss: 34242756608.0
Epoch 93
-------------------------------
loss: 34078224384.0
Epoch 94
-------------------------------
loss: 33914986496.0
Epoch 95
-------------------------------
loss: 33753026560.0
Epoch 96
-------------------------------
loss: 33592336384.0
Epoch 97
-------------------------------
loss: 33432909824.0
Epoch 98
-------------------------------
loss: 33274726400.0
Epoch 99
-------------------------------
loss: 33117788160.0
Epoch 100
-------------------------------
loss: 32962080768.0
Epoch 101
-------------------------------
loss: 32807593984.0
Epoch 102
-------------------------------
loss: 32654317568.0
Epoch 103
-------------------------------
loss: 32502243328.0
Epoch 104
-------------------------------
loss: 32351363072.0
Epoch 105
-------------------------------
loss: 32201666560.0
Epoch 106
-------------------------------
loss: 32053141504.0
Epoch 107
-------------------------------
loss: 31905785856.0
Epoch 108
-------------------------------
loss: 31759581184.0
Epoch 109
-------------------------------
loss: 31614521344.0
Epoch 110
-------------------------------
loss: 31470602240.0
Epoch 111
-------------------------------
loss: 31327809536.0
Epoch 112
-------------------------------
loss: 31186137088.0
Epoch 113
-------------------------------
loss: 31045576704.0
Epoch 114
-------------------------------
loss: 30906120192.0
Epoch 115
-------------------------------
loss: 30767757312.0
Epoch 116
-------------------------------
loss: 30630475776.0
Epoch 117
-------------------------------
loss: 30494269440.0
Epoch 118
-------------------------------
loss: 30359136256.0
Epoch 119
-------------------------------
loss: 30225057792.0
Epoch 120
-------------------------------
loss: 30092029952.0
Epoch 121
-------------------------------
loss: 29960050688.0
Epoch 122
-------------------------------
loss: 29829101568.0
Epoch 123
-------------------------------
loss: 29699180544.0
Epoch 124
-------------------------------
loss: 29570283520.0
Epoch 125
-------------------------------
loss: 29442390016.0
Epoch 126
-------------------------------
loss: 29315500032.0
Epoch 127
-------------------------------
loss: 29189607424.0
Epoch 128
-------------------------------
loss: 29064701952.0
Epoch 129
-------------------------------
loss: 28940773376.0
Epoch 130
-------------------------------
loss: 28817819648.0
Epoch 131
-------------------------------
loss: 28695828480.0
Epoch 132
-------------------------------
loss: 28574791680.0
Epoch 133
-------------------------------
loss: 28454707200.0
Epoch 134
-------------------------------
loss: 28335556608.0
Epoch 135
-------------------------------
loss: 28217348096.0
Epoch 136
-------------------------------
loss: 28100067328.0
Epoch 137
-------------------------------
loss: 27983704064.0
Epoch 138
-------------------------------
loss: 27868252160.0
Epoch 139
-------------------------------
loss: 27753701376.0
Epoch 140
-------------------------------
loss: 27640053760.0
Epoch 141
-------------------------------
loss: 27527297024.0
Epoch 142
-------------------------------
loss: 27415422976.0
Epoch 143
-------------------------------
loss: 27304427520.0
Epoch 144
-------------------------------
loss: 27194298368.0
Epoch 145
-------------------------------
loss: 27085035520.0
Epoch 146
-------------------------------
loss: 26976626688.0
Epoch 147
-------------------------------
loss: 26869067776.0
Epoch 148
-------------------------------
loss: 26762352640.0
Epoch 149
-------------------------------
loss: 26656477184.0
Epoch 150
-------------------------------
loss: 26551427072.0
Epoch 151
-------------------------------
loss: 26447202304.0
Epoch 152
-------------------------------
loss: 26343794688.0
Epoch 153
-------------------------------
loss: 26241198080.0
Epoch 154
-------------------------------
loss: 26139404288.0
Epoch 155
-------------------------------
loss: 26038409216.0
Epoch 156
-------------------------------
loss: 25938204672.0
Epoch 157
-------------------------------
loss: 25838786560.0
Epoch 158
-------------------------------
loss: 25740146688.0
Epoch 159
-------------------------------
loss: 25642283008.0
Epoch 160
-------------------------------
loss: 25545183232.0
Epoch 161
-------------------------------
loss: 25448847360.0
Epoch 162
-------------------------------
loss: 25353263104.0
Epoch 163
-------------------------------
loss: 25258428416.0
Epoch 164
-------------------------------
loss: 25164339200.0
Epoch 165
-------------------------------
loss: 25070989312.0
Epoch 166
-------------------------------
loss: 24978368512.0
Epoch 167
-------------------------------
loss: 24886468608.0
Epoch 168
-------------------------------
loss: 24795293696.0
Epoch 169
-------------------------------
loss: 24704833536.0
Epoch 170
-------------------------------
loss: 24615081984.0
Epoch 171
-------------------------------
loss: 24526034944.0
Epoch 172
-------------------------------
loss: 24437684224.0
Epoch 173
-------------------------------
loss: 24350023680.0
Epoch 174
-------------------------------
loss: 24263055360.0
Epoch 175
-------------------------------
loss: 24176764928.0
Epoch 176
-------------------------------
loss: 24091150336.0
Epoch 177
-------------------------------
loss: 24006207488.0
Epoch 178
-------------------------------
loss: 23921928192.0
Epoch 179
-------------------------------
loss: 23838314496.0
Epoch 180
-------------------------------
loss: 23755350016.0
Epoch 181
-------------------------------
loss: 23673040896.0
Epoch 182
-------------------------------
loss: 23591370752.0
Epoch 183
-------------------------------
loss: 23510347776.0
Epoch 184
-------------------------------
loss: 23429955584.0
Epoch 185
-------------------------------
loss: 23350192128.0
Epoch 186
-------------------------------
loss: 23271055360.0
Epoch 187
-------------------------------
loss: 23192539136.0
Epoch 188
-------------------------------
loss: 23114639360.0
Epoch 189
-------------------------------
loss: 23037345792.0
Epoch 190
-------------------------------
loss: 22960660480.0
Epoch 191
-------------------------------
loss: 22884575232.0
Epoch 192
-------------------------------
loss: 22809083904.0
Epoch 193
-------------------------------
loss: 22734184448.0
Epoch 194
-------------------------------
loss: 22659876864.0
Epoch 195
-------------------------------
loss: 22586146816.0
Epoch 196
-------------------------------
loss: 22512998400.0
Epoch 197
-------------------------------
loss: 22440419328.0
Epoch 198
-------------------------------
loss: 22368409600.0
Epoch 199
-------------------------------
loss: 22296965120.0
Epoch 200
-------------------------------
loss: 22226077696.0
Epoch 201
-------------------------------
loss: 22155745280.0
Epoch 202
-------------------------------
loss: 22085967872.0
Epoch 203
-------------------------------
loss: 22016733184.0
Epoch 204
-------------------------------
loss: 21948045312.0
Epoch 205
-------------------------------
loss: 21879889920.0
Epoch 206
-------------------------------
loss: 21812273152.0
Epoch 207
-------------------------------
loss: 21745182720.0
Epoch 208
-------------------------------
loss: 21678616576.0
Epoch 209
-------------------------------
loss: 21612572672.0
Epoch 210
-------------------------------
loss: 21547051008.0
Epoch 211
-------------------------------
loss: 21482037248.0
Epoch 212
-------------------------------
loss: 21417533440.0
Epoch 213
-------------------------------
loss: 21353537536.0
Epoch 214
-------------------------------
loss: 21290039296.0
Epoch 215
-------------------------------
loss: 21227038720.0
Epoch 216
-------------------------------
loss: 21164531712.0
Epoch 217
-------------------------------
loss: 21102518272.0
Epoch 218
-------------------------------
loss: 21040986112.0
Epoch 219
-------------------------------
loss: 20979935232.0
Epoch 220
-------------------------------
loss: 20919363584.0
Epoch 221
-------------------------------
loss: 20859269120.0
Epoch 222
-------------------------------
loss: 20799643648.0
Epoch 223
-------------------------------
loss: 20740483072.0
Epoch 224
-------------------------------
loss: 20681787392.0
Epoch 225
-------------------------------
loss: 20623550464.0
Epoch 226
-------------------------------
loss: 20565770240.0
Epoch 227
-------------------------------
loss: 20508442624.0
Epoch 228
-------------------------------
loss: 20451563520.0
Epoch 229
-------------------------------
loss: 20395128832.0
Epoch 230
-------------------------------
loss: 20339136512.0
Epoch 231
-------------------------------
loss: 20283584512.0
Epoch 232
-------------------------------
loss: 20228464640.0
Epoch 233
-------------------------------
loss: 20173774848.0
Epoch 234
-------------------------------
loss: 20119517184.0
Epoch 235
-------------------------------
loss: 20065683456.0
Epoch 236
-------------------------------
loss: 20012269568.0
Epoch 237
-------------------------------
loss: 19959273472.0
Epoch 238
-------------------------------
loss: 19906695168.0
Epoch 239
-------------------------------
loss: 19854526464.0
Epoch 240
-------------------------------
loss: 19802765312.0
Epoch 241
-------------------------------
loss: 19751411712.0
Epoch 242
-------------------------------
loss: 19700457472.0
Epoch 243
-------------------------------
loss: 19649904640.0
Epoch 244
-------------------------------
loss: 19599745024.0
Epoch 245
-------------------------------
loss: 19549978624.0
Epoch 246
-------------------------------
loss: 19500601344.0
Epoch 247
-------------------------------
loss: 19451613184.0
Epoch 248
-------------------------------
loss: 19403003904.0
Epoch 249
-------------------------------
loss: 19354779648.0
Epoch 250
-------------------------------
loss: 19306930176.0
Epoch 251
-------------------------------
loss: 19259453440.0
Epoch 252
-------------------------------
loss: 19212351488.0
Epoch 253
-------------------------------
loss: 19165618176.0
Epoch 254
-------------------------------
loss: 19119247360.0
Epoch 255
-------------------------------
loss: 19073241088.0
Epoch 256
-------------------------------
loss: 19027595264.0
Epoch 257
-------------------------------
loss: 18982305792.0
Epoch 258
-------------------------------
loss: 18937374720.0
Epoch 259
-------------------------------
loss: 18892791808.0
Epoch 260
-------------------------------
loss: 18848557056.0
Epoch 261
-------------------------------
loss: 18804670464.0
Epoch 262
-------------------------------
loss: 18761125888.0
Epoch 263
-------------------------------
loss: 18717921280.0
Epoch 264
-------------------------------
loss: 18675054592.0
Epoch 265
-------------------------------
loss: 18632523776.0
Epoch 266
-------------------------------
loss: 18590324736.0
Epoch 267
-------------------------------
loss: 18548457472.0
Epoch 268
-------------------------------
loss: 18506915840.0
Epoch 269
-------------------------------
loss: 18465701888.0
Epoch 270
-------------------------------
loss: 18424805376.0
Epoch 271
-------------------------------
loss: 18384232448.0
Epoch 272
-------------------------------
loss: 18343974912.0
Epoch 273
-------------------------------
loss: 18304036864.0
Epoch 274
-------------------------------
loss: 18264408064.0
Epoch 275
-------------------------------
loss: 18225090560.0
Epoch 276
-------------------------------
loss: 18186076160.0
Epoch 277
-------------------------------
loss: 18147373056.0
Epoch 278
-------------------------------
loss: 18108966912.0
Epoch 279
-------------------------------
loss: 18070863872.0
Epoch 280
-------------------------------
loss: 18033059840.0
Epoch 281
-------------------------------
loss: 17995548672.0
Epoch 282
-------------------------------
loss: 17958332416.0
Epoch 283
-------------------------------
loss: 17921406976.0
Epoch 284
-------------------------------
loss: 17884768256.0
Epoch 285
-------------------------------
loss: 17848418304.0
Epoch 286
-------------------------------
loss: 17812353024.0
Epoch 287
-------------------------------
loss: 17776570368.0
Epoch 288
-------------------------------
loss: 17741064192.0
Epoch 289
-------------------------------
loss: 17705836544.0
Epoch 290
-------------------------------
loss: 17670885376.0
Epoch 291
-------------------------------
loss: 17636206592.0
Epoch 292
-------------------------------
loss: 17601798144.0
Epoch 293
-------------------------------
loss: 17567660032.0
Epoch 294
-------------------------------
loss: 17533788160.0
Epoch 295
-------------------------------
loss: 17500182528.0
Epoch 296
-------------------------------
loss: 17466836992.0
Epoch 297
-------------------------------
loss: 17433753600.0
Epoch 298
-------------------------------
loss: 17400928256.0
Epoch 299
-------------------------------
loss: 17368360960.0
Epoch 300
-------------------------------
loss: 17336043520.0
Epoch 301
-------------------------------
loss: 17303984128.0
Epoch 302
-------------------------------
loss: 17272172544.0
Epoch 303
-------------------------------
loss: 17240608768.0
Epoch 304
-------------------------------
loss: 17209292800.0
Epoch 305
-------------------------------
loss: 17178220544.0
Epoch 306
-------------------------------
loss: 17147392000.0
Epoch 307
-------------------------------
loss: 17116804096.0
Epoch 308
-------------------------------
loss: 17086456832.0
Epoch 309
-------------------------------
loss: 17056344064.0
Epoch 310
-------------------------------
loss: 17026469888.0
Epoch 311
-------------------------------
loss: 16996826112.0
Epoch 312
-------------------------------
loss: 16967412736.0
Epoch 313
-------------------------------
loss: 16938231808.0
Epoch 314
-------------------------------
loss: 16909277184.0
Epoch 315
-------------------------------
loss: 16880551936.0
Epoch 316
-------------------------------
loss: 16852046848.0
Epoch 317
-------------------------------
loss: 16823764992.0
Epoch 318
-------------------------------
loss: 16795708416.0
Epoch 319
-------------------------------
loss: 16767866880.0
Epoch 320
-------------------------------
loss: 16740241408.0
Epoch 321
-------------------------------
loss: 16712834048.0
Epoch 322
-------------------------------
loss: 16685641728.0
Epoch 323
-------------------------------
loss: 16658660352.0
Epoch 324
-------------------------------
loss: 16631888896.0
Epoch 325

In [569]:
13353574400 > 12765857792

True

In [570]:
model(x_train_tensor)

tensor([[208924.3906],
        [182800.1250],
        [213955.0625],
        ...,
        [207353.6094],
        [194474.3125],
        [215722.5781]], grad_fn=<AddmmBackward0>)

In [571]:
y_train_tensor

tensor([216300., 178600.,  74700.,  ..., 228200., 181800., 225900.])

In [573]:
y

0        164600.0
1        125000.0
2        244500.0
3        106300.0
4        265800.0
           ...
16507    111500.0
16508    238700.0
16509    275000.0
16510    150400.0
16511    133900.0
Name: median_house_value, Length: 16512, dtype: object

In [575]:
features = df.drop("median_house_value", axis=1)
labels = df["median_house_value"]

In [581]:
from part2_house_value_regression import Regressor

regressor = Regressor(features)

regressor.fit(features, labels)

TypeError: Regressor.__init__() missing 1 required positional argument: 'y'